name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build JAR
      run: mvn clean package

    - name: Login to ACR
      run: |
        docker login ${{ secrets.ACR_LOGIN_SERVER }} \
        -u ${{ secrets.ACR_USERNAME }} \
        -p ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/javaapp:v1 .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/javaapp:v1

    - name: Setup Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
